### PR TITLE
feat: add preprod and preview networks

### PR DESCRIPTION
**Pull request by wolf31o2**
Signed-off-by: Chris Gianelloni <cgianelloni@cloudstruct.net>

### CODE REVIEW

**Comment by lsdbitrue** [comment]
Thanks for the contribution.

Do you have a documentation about the new network?

**Comment by wolf31o2** [comment]
https://book.world.dev.cardano.org/environments.html#preview-testnet

**Comment by lsdbitrue** [comment]
Do you also have a documentation about the network id?

**Comment by wolf31o2** [comment]
I fetched them from the byron-genesis.json from each network on the above page.

**Pull request merged**
